apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radarr-cert
  namespace: radarr
spec:
  secretName: radarr-cert
  dnsNames:
  - radarr.chowned.net
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io