apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: radarr
  namespace: radarr
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       radarr
  updatePolicy:
    updateMode: "Auto"