cilium:
  hubble:
    relay:
      enabled: true
    ui:
      enabled: true
  ipam:
    mode: kubernetes
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  securityContext:
    privileged: true
  