overseerr:
  dnsConfig:
    options:
      - name: ndots
        value: "1"
  image:
    tag: latest
    pullPolicy: Always
  env:
    TZ: America/New_York
  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: request.chowned.net
          paths:
            - path: /
              pathType: Prefix
      tls:
      - secretName: overseerr-cert
  persistence:
    config:
      enabled: true
      storageClass: "rook-ceph-block"
    datastore:
      enabled: true
      type: hostPath
      hostPath: /nasv3/datastore/
      mountPath: /datastore
  resources:
    requests:
      cpu: 100m
      memory: 256Mi