metallb:
  configInline:
    address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 192.168.1.50-192.168.1.55
  prometheusRule:
    enabled: true
  controller:
    prometheus:
      serviceMonitor:
        enabled: false
  speaker:
    prometheus:
      serviceMonitor:
        enabled: false