apiVersion: v2
name: metrics-server
description: metrics-server
version: v6.0.9
appVersion: v0.6.1
dependencies:
- name: metrics-server
  version: 6.2.0
  repository: https://charts.bitnami.com/bitnami