calibre:
  envFrom:
    - secretRef:
        name: calibre-env
  image:
    repository: linuxserver/calibre
    tag: version-v5.21.0
  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.middlewares: chowned@file
      hosts:
        - host: calibre.chowned.net
          paths:
            - path: /
              pathType: Prefix
      tls:
      - secretName: calibre-cert
  persistence:
    rtorrent:
      enabled: true
      type: custom
      volumeSpec:
        nfs:
          server: 192.168.1.22
          path: /datastore/rtorrent
      mountPath: /rtorrent
    calibre:
      enabled: true
      type: custom
      volumeSpec:
        nfs:
          server: 192.168.1.22
          path: /datastore/calibre
      mountPath: /datastore/calibre
    calibre-config:
      enabled: true
      type: custom
      volumeSpec:
        nfs:
          server: 192.168.1.22
          path: /datastore/calibre/calibre-config
      mountPath: /config
  probes:
    liveness:
      enabled: false
  podSecurityContext:
    supplementalGroups:
      - 100
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
  service:
    webserver:
      enabled: true