apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lidarr-cert
  namespace: lidarr
spec:
  secretName: lidarr-cert
  dnsNames:
  - music.chowned.net
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io