apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: lidarr
  namespace: lidarr
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       lidarr
  updatePolicy:
    updateMode: "Auto"