apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tautulli-cert
  namespace: tautulli
spec:
  secretName: tautulli-cert
  dnsNames:
  - plexpy.chowned.net
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io