apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: kube-system
spec:
  schedule: '@hourly'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              # Update this to the latest available and then enable Renovate on
              # the manifest
              image: renovate/renovate:37.50.2
              args:
                - ag237/argocd
                - ag237/portainer
              # Environment Variables
              env:
                - name: LOG_LEVEL
                  value: info
              envFrom:
                - secretRef:
                    name: renovate-env
          restartPolicy: Never