apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: plex-meta-manager
  name: plex-meta-manager
  namespace: plex-meta-manager
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
