radarr-4k:
  env:
    TZ: America/New_York
  image:
    repository: ghcr.io/k8s-at-home/radarr
    tag: v4.1.0.6175
  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.middlewares: chowned@file
      hosts:
        - host: radarr-4k.chowned.net
          paths:
            - path: /
              pathType: Prefix
      tls:
      - secretName: radarr-4k-cert
  nameOverride: "radarr-4k"
  persistence:
    config:
      enabled: true
      storageClass: "rook-ceph-block"
    datastore:
      enabled: true
      type: hostPath
      hostPath: /nasv3/datastore
      mountPath: /datastore
  probes:
    liveness:
      enabled: false
  podSecurityContext:
    supplementalGroups:
      - 100
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
  # initContainers:
  # - name: update-volume-permission
  #   image: busybox
  #   command: ["sh", "-c", "chown -R 568:568 /config"]
  #   volumeMounts:
  #   - name: config
  #     mountPath: /config
  #   securityContext:
  #     runAsUser: 0