traefik:
  deployment:
    kind: DaemonSet
  envFrom:
    - secretRef:
        name: namecheap-creds
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
  service:
    spec:
      loadBalancerIP: "192.168.1.50"
      externalTrafficPolicy: Local
  ports:
    web:
      redirectTo: websecure
    metrics:
      expose: true
  ingressRoute:
    dashboard:
      enabled: false
  logs:
    access:
      enabled: true
    general:
      level: ERROR
  volumes:
    - mountPath: /dynamic-config
      name: config-yaml
      type: secret
    - mountPath: /etc/traefik
      name: traefik-yaml
      type: secret