traefik:
  # additionalArguments: 
    # - "--api.insecure=true"
    # - "--accesslog.fields.headers.defaultmode=keep"
    # - "--entryPoints.web.forwardedHeaders.trustedIPs=127.0.0.1/32,192.168.1.1/24"
    # - "--entryPoints.websecure.forwardedHeaders.trustedIPs=127.0.0.1/32,192.168.1.1/24"
    # - "--providers.file.directory=/config"
    # - "--providers.file.watch=true"
    # - "--providers.kubernetesingress.ingressclass=traefik"
    # - "--providers.kubernetesingress.ingressendpoint.publishedservice=traefik/traefik"
    # - "--metrics.prometheus=true"
    # - "--metrics.prometheus.entryPoint=web"
    # - "--certificatesresolvers.namecheap.acme.email=agentgreen@gmail.com"
    # - "--certificatesresolvers.namecheap.acme.storage=/data/acme.json"
    # - "--certificatesresolvers.namecheap.acme.caserver=https://acme-v02.api.letsencrypt.org./directory"
    # - "--certificatesresolvers.namecheap.acme.dnschallenge.provider=namecheap"
    # - "--certificatesresolvers.namecheap.acme.dnschallenge.delaybeforecheck=0"
    # - "--certificatesresolvers.namecheap.acme.dnschallenge.resolvers=156.154.132.200:53,156.154.133.200:53"
  deployment:
    initContainers:
      # The "volume-permissions" init container is required if you run into permission issues.
      # Related issue: https://github.com/containous/traefik/issues/6972
    - name: volume-permissions
      image: busybox
      command: ["sh", "-c", "chmod -Rv 600 /certs/*"]
      volumeMounts:
        - name: certs
          mountPath: /certs
  envFrom:
    - secretRef:
        name: namecheap-creds
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1
  # ingressClass:
  #   enabled: true
  #   isDefaultClass: true
  persistence:
    enabled: true
    path: /certs
    name: certs
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  service:
    spec:
      loadBalancerIP: "192.168.1.50"
      externalTrafficPolicy: Local
  ports:
    web:
      redirectTo: websecure
  ingressRoute:
    dashboard:
      enabled: false
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 300
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 150
  logs:
    access:
      enabled: true
    general:
      level: DEBUG
  volumes:
    - mountPath: /dynamic-config
      name: config-yaml
      type: secret
    - mountPath: /etc/traefik
      name: traefik-yaml
      type: secret