apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: config-yaml
  namespace: traefik
spec:
  encryptedData:
    config.yaml: AgAJ185GBsI7X0f8WSZsnTS6pzHU/uqCsOJw1cD4JJKM3LzXAeeH3E29UpK/cH2SygvTN+btA/8IPJx0RJ+T1AEjnsvklFHL5kGhY3jJLcWM57oPfOxt3nDBJs+YAO+Hb08bzQMQqtnY4wr2nqcgdAcMr24EKi7VkHqTXm3Sl84fZ0bnzASocuHbGWQe947+ybC1hivXDlIMs46jzuXoU1k7qQ7fsIWAeYyFI1re8DsnI/GFnuVrHjchksQN35lgdA8hMCuBzjHQcWtqv5IPSZ/msMVC8UUFM0cHWo62BNF/MBSAXSNROIXp2fvRmt8Qhol6wf09sXTMiZ2JXpB+iMQKgVSDtmhCZlW6/VAjfU8VxZ3+mBAgbTZpm/rADyxzYgHBjHr6d3t3PKT2Htlk9k2T7te6xNs7T5ojQSGbKc7UtBaPpvBOT5KzzlRG43mQdUZsdp+OQ2bVKJ+30niJTFHo3OJ7NTdC2lDyAgruuL2GJmQgxJfPPuvYo+OxQEpKjbxdZieA9ApLt9RNWDhRq9uGdoFdmpWWepeMmBOo36rq07JviyyJVzxQ1JS8O+OLym1ISksu39Zg+xy6jXRjWeOTcaieXZhhiT7LVCFGTjW2K+CjnCI/U6DXzS09R0ZAMa5xgr6GR8//EUa7oZGANC93m767epIVBhmq2cUNASqCMxGn0TIWMolnumBX4O7V2Jn46YZLq6UmmQe4ow/ZypFSRzVAr4m6UcRvCvimFbygGmFCXJL38096/nZ+tv5KcKTpACN4BBGAuNMriCvo1XnqJo+qs6NXRwoLOAWjzHzD9pyuOY2atUE1QpsAnPiCC4tu1ISJtVQDQJ+JON6qsIeg9Vuxhs+8AvyKm8ICJ5Mpbh+6o/M7HOkN/G2j6arWBq1TYQkMMVV3NW4ki7YafAUKRPZICCnbE9IE2eWcyWBWj2atF3Yr2DkDs5Z8MyO8MrjG9dPcD45JbUio8dLobIsLeVqbBTslzJmbEj1UbL+FnmIaBa1WD3LiS/izl2LfUeSKMwUHBvBwP56AcrBO9GFt402IV/nAAPfe5iWK1Vk68t35qIIOqe1u93HMK1Pdh7uFpu5xfjJHk1MVPczVK+hmN1rXVR+GLHHYRRobI7gM0lWWSwLhwfLW7U4uZ0mxiuL82RFy9TRWgHs3JstOyMpZCw+sejGf8E1DX40l+6uVYbKqzvTOYtnorcr77Dmd0ZBjHIa0P/P5kknbpUWATnh4QwUnX3VTnKSqP2p/ZgoY2eaLbwlJVpG2AuscYud0EMsF00I7jNkgmpx8Q/1XeWVNUbDO+rvObjUvwBzAJoGWbNqHYbffISigOKDwHfhRF7VzBSc+fG+9KsJxbl74lq8OhSIZSYTqWhoCssZjJGO7koXSxkMNa8/QZkRJnsHAPzt/kIfhudQCGE2mY+ix43RxAQzUxxSIkWDoDN+tc16q0RBRHEZU+ielZAhr0C5XInM4IVA8EzvccS8zCetgILthcPq/RVqYtZE=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: config-yaml
      namespace: traefik

