apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: config-yaml
  namespace: traefik
spec:
  encryptedData:
    config.yaml: AgCaRXEPVdDUmxKmR7uNXZcxd3VQ5Nl7dyXqoz1WUDkpeYbhbtPFGIuPmrHflQG5ZERMlJ/ZOZUZYyi6TUQ7UTwbN0so7ao7qlwHha2oWBe5QWw9rxgGcPpJXgq/B0Gobz2Z5fXDTDmIfodiu4LGBN2rfvgFyz+I5nqXOSRVyjfPD/DXecrCLMXgyjFkHkJbyoDJfeDmJzJNEemwoHevaHXaJBEMKzLNBV+lGCwYL/j9wRvoc/xbXWzlB3oGXh/JTm8kpAopQISJVaMDqU91pQWDj9ypQBugRNbMl3kARQtK/pHVhzpU6P/SNxaaEBlHWCB6X3PS7286OWL1PnS2fo8/sx3kK36sdWa4rfBRaFVzqXuIt5MQ9RT23n9El2zVUwnKdwsZy4tG+vwwHemkaLF5S6yfxUUhoxHQwkFFxkUMWlJcmIK40LjtYmaIqGx69ZWUNUFWGttR74SMIZGuXufcIN/a4eDv8Jn+gPwTabXAB21xzQgwXMQf90X7OEZAaQt0bNcU7Y/QMWbzdC/tDpljzBhX6gdP/DdY6V/P8V7BbvQbMsuA+/b9TS27UCS1OeIue/cJonoosoel84Fg+Tmvh5y8Nyr9MtqLw7L9hByMe0zGsHRY7XJ0tH985iCwde/ksCHuCFOStpCtgrtUXt5SctCalvXll2MUvFtUPZxnguFj0WiArL/dlwR2765jlzO38Dvg2PNAJWLWv8uXML2XSHY5xA9BGzYKQUCb7nMHeuwFHJFkukMb819DVf1fvCIrtGaMpcaV8mwFs9EW3K0S1ukyALXMN6PFSXPiziQMGSf5s4m94rl5B4zqTQN4FRsB0Wpl9k5B+FFMmdkMXYwzOX7p/6K3bg5AVwEJV74L3MZ9AUIE2dO5rOEX92Lw9+vy1FxnoMWONEiZb/QU3c38sKlsBAOgBMhPXxrAslLTxGr9jn2cyYGpDsXM7YWQZt15zgObvW6JtPAhxleaHw3yjt1tLy+jfHk8IhdRtQ/vLjU9pE9BZt95nohSrqZL3lSojL58TpulTWzUQWflwV6jymDjCfKpx9fYSImCStO8qNLsxjJ4TfyC0W2oawlvpkm5Tkj7HjHx/BWPc0wTCSBuM1HZlMVNMC4w0bwzsd4H1Qy6QVqSlPlzBkDrRuYRzSAuIR1JOcH1i3SzS8kMcx6hQSfUOFAsET4kDV0maoE0P+h3BlUbPNL90mx8dxNOpTxd5I4b1d5La6fWsuu0ZbjXUX9khgZB0TqEJu6ZakA7kSO1yP0AK0SAizpmAOs8YrZekTkH55PUS0V3FVwJPwYIAi1Vk/m6CvpGcQCYZmHqwoLAtKdhwn7sO6E4VxSvZtz5/7Xe4Dx0qBUIc6HGoBxlsLXibtE5NqX5ObG8+XBimMe72WgZYCnUTceJMVoCnwuAFQNvPfH46WMosgUySZrtT1WAeaeOfRPDqZ0VtbZTLWS7UCygCRvbO2qdw3MXTqaAYI8cvxj8Ed/42a9Vi7lXzlaK
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: config-yaml
      namespace: traefik

