kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: portainer
  name: portainer
  namespace: traefik
spec:
  type: ExternalName
  ports:
    - name: portainer
      port: 9000
      targetPort: 9000
  externalName: 192.168.1.22
  selector:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: portainer
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`portainer.chowned.net`)
      kind: Rule
      services:
        - name: portainer
          kind: Service
          port: 9000
  tls: {}