apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radarr-4k-cert
  namespace: radarr-4k
spec:
  secretName: radarr-4k-cert
  dnsNames:
  - radarr-4k.chowned.net
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io