metallb:
  prometheusRule:
    enabled: true
  controller:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  speaker:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true