sonarr-4k:
  env:
    TZ: America/New_York
  image:
    tag: latest
    pullPolicy: Always
  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.tls.certresolver: namecheap
        traefik.ingress.kubernetes.io/router.middlewares: chowned@file
      hosts:
        - host: sonarr-4k.chowned.net
          paths:
            - path: /
              pathType: Prefix
  nameOverride: sonarr-4k
  persistence:
    config:
      enabled: true
      storageClass: "rook-ceph-block"
      size: 2Gi
    datastore:
      enabled: true
      type: hostPath
      hostPath: /nasv3/datastore
      mountPath: /datastore
  probes:
    liveness:
      enabled: false
  podSecurityContext:
    supplementalGroups:
      - 100
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 256Mi