apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarr-cert
  namespace: sonarr
spec:
  secretName: sonarr-cert
  dnsNames:
  - sonarr.chowned.net
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io