apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: sonarr
  namespace: sonarr
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       sonarr
  updatePolicy:
    updateMode: "Auto"