apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: homepage
    repoURL: https://github.com/ag237/argocd.git
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: homepage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true