apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://nextcloud.github.io/helm/'
    targetRevision: 3.3.4
    helm:
      values: |
        image:
          repository: nextcloud
          tag: 25.0.1
          # tag: 25.0.1-fpm-alpine
          # flavor: fpm-alpine
          pullPolicy: IfNotPresent
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: traefik
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: "true"
            traefik.ingress.kubernetes.io/router.middlewares: chowned@file
          hosts:
            - host: nextcloud.chowned.net
              paths:
                - path: /
                  pathType: Prefix
          tls: {}
        externalDatabase:
          enabled: false
          existingSecret:
            enabled: true
            secretName: nextcloud-secrets
            usernameKey: nextcloud-username
            passwordKey: postgres-nextcloud-password
        nextcloud:
          host: nextcloud.chowned.net
          existingSecret:
            enabled: true
            secretName: nextcloud-secrets
            usernameKey: nextcloud-username
            passwordKey: postgres-nextcloud-password
          extraVolumes:
            - name: datastore
              nfs:
                server: "192.168.1.22"
                path: "/datastore/nextcloud/data"
          extraVolumeMounts:
            - name: datastore
              mountPath: /data
        nginx:
          enabled: false
        internalDatabase:
          enabled: false
        postgresql:
          enabled: true
          global:
            postgresql:
              auth:
                username: "nextcloud"
                database: "nextcloud"
                existingSecret: "nextcloud-secrets"
                secretKeys:
                  adminPasswordKey: "postgres-password"
                  userPasswordKey: "postgres-nextcloud-password"
          primary:
            persistence:
              enabled: true
              size: 50Gi
        redis:
          enabled: false
          auth:
            enabled: true
            existingSecret: "nextcloud-secrets"
            existingSecretPasswordKey: "redis-password"
        cronjob:
          enabled: true      
        persistence:
          enabled: true
        phpClientHttpsFix:
          enabled: true
        resources:
          limits:
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 256Mi
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
            namespace: nextcloud
        startupProbe:
          enabled: true
    chart: nextcloud
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nextcloud
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true