apiVersion: v2
name: kube-prometheus-stack
description: kube-prometheus-stack
version: 33.2.0
appVersion: 0.54.1
dependencies:
- name: kube-prometheus-stack
  version: 35.3.0
  repository: https://prometheus-community.github.io/helm-charts