apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prowlarr-cert
  namespace: prowlarr
spec:
  secretName: prowlarr-cert
  dnsNames:
  - prowlarr.chowned.net
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io