apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: overseerr-cert
  namespace: overseerr
spec:
  secretName: overseerr-cert
  dnsNames:
  - request.chowned.net
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io