apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: tdarr
  namespace: tdarr
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       tdarr
  updatePolicy:
    updateMode: "Auto"