apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarr-4k-cert
  namespace: sonarr-4k
spec:
  secretName: sonarr-4k-cert
  dnsNames:
  - sonarr-4k.chowned.net
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io