apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: default
spec:
  encryptedData:
    api-token: AgCSvAIwNbLZbu4IvUQhivPZZXf7YJoqlBrHVfTQb8cofcabZCrME5YUlVtlxEk8hS+OC/iYXLmTVbMcwCO6UY7EcTruYytFSw1+aHHWK0O9JhNjvZrN1eBKNWpBqj6pevKBAaA33NoerchWHLQ1EvPx2pHGgU87BckhRyZ6Cd6b5AAoQnEj0Ii5rPcgsGJzaOnu7IeVGT97ctmQzDMo6DlvBCabzCKnFSKpjxATPZeXFS3Um+NVwn4Xzh7nxRj91qautdzNQqGV/3ifsdH5lnMbYTZWq1ZzmpWcdHWZbw48J3hxPZNwcy9nG1ohbhv/WndFuP8kmx/fPHqFLaGadBs1ZAP/oWjHHW/GxaLEs5Pqg7BKDzQhA9+wJs/7v39PmF83snShv5oDEoZ1KiVhDTHtpsC1l2eANVLaw43OZGi4+VE763XLdrhf+4C/ol6byopXBT7QL7N4G1rNG+ho4O7SSWoKC73dufBWLzqePfvMzzpW5U6b2ZJvUnTrlQ4BSWV6SRKxqJDUKOx6pOcyd4YBjREQM5b1l4MHvJram3RbyBa7YKaWnYnQksfWLE/wXdoO8sLLq2RYyY6Ip/Fbjf0JsSrE9KNiaD35aTDXbaqbVFA3ZQZv1ftD18u0RrQPHmPKvzeT5l8d6yGh3/DiCGahEfKfA8c9dAagR9Whlfll+eN6vI+IZAWi40fMCnEUgViT1kw7WBJYEMBQkpbEF8d++l4o9QdEYM7IOD+3WdRaWysHUeWE/Q35
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: default
    type: Opaque

