apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgDTrPkYWtkdpcRVP4U5IX59D3DAPCI/loclwZXHWI3LMkG3l9kiKuEsLlSdWNv2fx4kZwPudh1dKBuGQSWPume6HsKCXhcC5mFvvBOaY+JTuGGpE1KUcVzoVIMmmlkp/drGZRsnL3CBwTZrJq3cDQsgrgCh5oB+zGfUkPpWTgX11x/LKUMnNqQLi0Z5BDNdux3ASfM3l1OYjKGxw4PdywMdemf+vlKj9vWR4B9rvqa+h2IlsRnezOxLDn/BHNT7sQsIRR+sT8DS0r6p00ataVBYL9T7G3UCpgVVNJYeJk/6B9Lp4DeENf0LQBWSm1wSuh5HI/592rXypFzOv/a/ATfyXBAfuQWuRNnc0u1BHEM+2nRBNtcr4f2nK+HpiCBptrstZJFhG4eOSbJgbzN8Gk2Oi7KdhZCxqskXbZ97tJnZCQN/jKQYKJDFBlW+rDUIJ3b+VdJrZiAoFPuGT2nFrGZ8Gxm4St1Pf76VjHuF4uVbJgS5BvxVIKU397NCD6cbRCuX/U6KKzvBwk0V6wX6NvvdLpBoyFCoq9WjXs0n7Gq1NR0iIKMQan0tgUF/PQtxBHjawFUYJO2qsyhjwpFKQAIEijT5Bak1jHELaeGpMgbVDwcWSAkv4ANK1CR5ZwHyJvSW0IoxJYbyYr9NLURj1pBPYQ+Wg44/YBEoAWP3+pHLxzhY66bhP0OT9Iz9ozj24WhSARaiJLkwWj+CMUihgh03wLG+Ng/badvgMtNXIKKLBKRr6UvCvLOr
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque

