apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: agentgreen@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production-key
    solvers:
    - dns01:
        cloudflare:
          email: agentgreen@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token