apiVersion: v2
name: sealed-secrets
description: sealed-secrets
version: 2.1.3
appVersion: v0.17.3
dependencies:
- name: sealed-secrets
  version: 2.6.3
  repository: https://bitnami-labs.github.io/sealed-secrets