apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: readarr-cert
  namespace: readarr
spec:
  secretName: readarr-cert
  dnsNames:
  - books.chowned.net
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io