apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: readarr
  namespace: readarr
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       readarr
  updatePolicy:
    updateMode: "Auto"