apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: calibre-cert
  namespace: calibre
spec:
  secretName: calibre-cert
  dnsNames:
  - calibre.chowned.net
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io