apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: calibre
  namespace: calibre
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       calibre
  updatePolicy:
    updateMode: "Auto"