apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: plex-media-manager
  name: plex-media-manager
  namespace: plex-media-manager
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
