apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: base
spec:
  generators:
  - git:
      repoURL: https://github.com/ag237/argocd.git
      revision: HEAD
      directories:
      - path: charts/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/ag237/argocd.git
        targetRevision: HEAD
        path: '{{path}}'
      syncPolicy: {}
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'