apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rook-dashboard-cert
  namespace: rook-ceph
spec:
  secretName: rook-dashboard-cert
  dnsNames:
  - rook-dashboard.chowned.net
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io